### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by bumbeishvili** [bumbeishvili/d3-upw-jake-tz-infogr8-odi-scatter-landing#1]
# Milestone 3. Testing & Feedback & Handover
* [ ] Handover
* [x] Testing
* [x] Feedback
* [x] Fill [Handover Form](https://docs.google.com/document/d/1JHKD4pWg0EkxCbn25yKLBiaLqskiC-BveXvY5_3WpOQ/edit)

## Resources

* [ Landing Page Template ](https://tailwindtoolbox.github.io/Landing-Page/#)
* [Tailwind CSS](https://tailwindcss.com/)
* [Designs](https://www.figma.com/file/pLiGcnXqxgrQXMz3zWol2X/181_ODI-tool-wireframe_v1?node-id=383%3A680)
* [Brand Guidelines](https://docs.google.com/presentation/d/1KH5ZjhhnsN85v8bpHxjDGGFmpTgLKUKPfo0Zv-6H55M/edit#slide=id.ge3bf7c02c2_0_0)
* [Project overview and plan](https://docs.google.com/document/d/1VaK9DdJg2yThaCShd9ZAL8sU4EDLMGPxv8tzjPOAHB8/edit)
* [Slack](https://app.slack.com/client/T01PZ1JF7FY)
* [Tailwind Toolbox](https://www.tailwindtoolbox.com/starter-components)
* [Data - Country profiles](https://drive.google.com/drive/folders/1VwhtF_JuSxJWB-Cpgf5OnHQBWDB0JfX7)
* [ Serif Template - Jekyll](https://github.com/zerostaticthemes/jekyll-serif-theme)
* [Initial Email](https://mail.google.com/mail/u/1/#search/jake/FMfcgzGkbDThgTdvsZZLSDCfbPwcwPTm)
* [Questions Doc](https://docs.google.com/document/d/1yqZAsGpS2oEVHUbATx5aPmi1CwcSVHPj3UQM7Ianztg/edit?usp=sharing)
* [PDF Feedback](https://infogr8workspace.slack.com/files/U01QBV9N9FE/F02FEUFM5NY/links_and_feedback.pdf)
* [Feedback Docs](https://docs.google.com/document/d/1yqZAsGpS2oEVHUbATx5aPmi1CwcSVHPj3UQM7Ianztg/edit)

## Feedback

**Final Remaining Issues**
* [x] PDF - Explore the report - video 
* [x] Video Embed for the explore report page
* [x] Fill placeholder buttons with URLs
* [x] List styling issues

ODI

* [x] PDF - Logo
* [x] PDF - Links
* [x] PDF - Contact/Involved
* [x] Pdf - the "Contact us" Tool
* [x] Pdf - manifesto order
* [x] Pdf - rounding
* [x] Pdf - Methodology link
* [x] Pdf - sentence
* [x] Pdf - Country Profiles
* [x] Pdf - Further Resources - Remove bar
* [x] Pdf - Further Resources -Link
* [x] Export - Add info panel
* [x] Export - remove labels
* [x] Export - fix fonts/ use Arial
* [x] Export - flags
![image](https://user-images.githubusercontent.com/6873202/134686243-0c999f3b-07c0-490f-89ec-fca91dcaf4be.png)
* [x] Include GIF file
* [x] Get Involved text
* [x] Generalize comparison percents
* [x] PDF - content on every page
* [x] PDF - HOME TEXTS
* [x] PDF - Explore the report - texts
* [x] PDF - Methodology texts
* [x] #2
* [x] Get involved text
* [x] Social media handles (twitter,fb,linkedin)
* [x] Add explore the data menu
* [x] Swap limited vision and less prepared
* [x] Replace regions and countries
* [x] Add overall score in scatter chart
* [x] ![image (1)](https://user-images.githubusercontent.com/6873202/134687958-20445eec-15e4-480b-b50b-6d42b3062cee.png)
* [x] Gif
* [x] Google Analytics
* [x] Image for the report section
* [x] EU Cards
* [x] Download report text `Download our report to explore the data, and for key insights on the European policy landscape. Discover how different stakeholder communities can work together for an open and trustworthy data ecosystem for secondary use of health data in Europe.`
* [x] <img width="517" alt="Screenshot 2021-09-27 at 13 27 42" src="https://user-images.githubusercontent.com/6873202/134882421-d04f049f-3ae4-4ce8-8b2c-fc51aa44634f.png">

## Me
* [x] Cards => Link => Not working correctly
* [x] Comparison - Collapsible - empty content
* [x] Mobile Fix EU Commission

## Jake
* [x] Review all typography weights to match the designs 
* [x] ‘Reset filters’ should not appear if no filter is selected
* [x] Filters should show what you’ve selected 
* [x] Figures should be percentages not out of 100 e.g 74/100 should be 74% 
* [x] ~Four quadrants need ‘i’ label e.g. ‘Leaders’ needs an ‘i’ next to it~
* [x] Spell out all countries in full e.g. United Kingdom
* [x] Add hover states overrank mode and comparison mode to show that it’s clickable 
* [x] European Union should be selected by default 
* [x] Filters not clickable above the scattergraph
* [x] Filters deselecting the wrong items
* [x] Deselect all should not be visible when nothing clicked
* [x] Overview text should be black
* [x] No vertical line on the left 
* [x] Hover state on country profiles accordion should be bold 
* [x] Filters not working 
* [x] Overview text should be black
* [x] No vertical line on the left 
* [x] Hover state on country profiles accordion should be bold 
* [x] “Evaluation against success indicator” needs to be the same styling as “Stage of implementation” 
* [x] Switch Colors in a comparison module

# Milestone 2. Page Building
* [x] Initial boilerplate page
* [x] Initial placeholder texts
* [x] Implementing Smooth Page Changes
* [x] Include Visualization On sample data
* [x] Analyse Data
* [x] Implement header
* [x] Implement footer
* [x] Home - HTML
* [x] Explore The Report Page - HTML
* [x] Methodology - HTML
* [x] Further Resources - HTML
* [x] Get Involved - HTML
* [x] Contact US - HTML
* [x] Fill Data
* [x] Explore Data - Rank - HTML
* [x] Explore Data - Rank - Overall Score Modes
* [x] Explore Data - Rank - Filter modes
* [x] Explore Data - Rank -  Regions by overall score
* [x] Explore Data - Rank - Overall Score Modes
* [x] Explore Data - Comparison - HTML
* [x] Explore Data - Rank - Categories
* [x] Explore Data - Rank - Filter/Sort Modes
* [x] Explore Data - Rank -  Comparing - Accordions
* [x] Explore Data - Rank - Comparing - Cards
* [x] Make mobile friendly
* [x] Export
* [x] FB Share Image

# Milestone 1.

* [x] Setting up
* [x] Infogr8 Repo
* [x] Reviewing Designs
* [x] Data review
* [x] Setting Up github repo
* [x] Setting Up data viz page & Urls

Column Generation
```javascript
document.body.innerHTML = `
<table>
<tr>
${"Capability Engagement Ethics Equity Infrastructure Innovation".split(/\s/).map(d=>d.toLowerCase()).map(d=>d+"ImplementationSpeed").map(d=>`<td>${d} &nbsp;</td>`).join('')}
</tr>
</table>

`
```

Rachels Email
`rachel.wilson@theodi.org`

**Comment by bumbeishvili** [comment]
cec qqc≈XACAc
